# Generated by Django 5.0.6 on 2024-06-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_teacher', models.CharField(max_length=20)),
                ('course_duration', models.PositiveIntegerField()),
                ('course_level', models.PositiveSmallIntegerField()),
                ('course_resources', models.CharField(max_length=50)),
                ('course_description', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=40)),
                ('course_objectives', models.CharField(max_length=20)),
                ('course_category', models.CharField(max_length=20)),
                ('course_id', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
