# Generated by Django 5.0.6 on 2024-07-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_category',
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_duration',
            field=models.TimeField(),
        ),
    ]
