# Generated by Django 5.0.6 on 2024-07-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='class_teacher',
        ),
        migrations.AlterField(
            model_name='class',
            name='class_goal',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='class_vision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='class',
            name='meetings',
            field=models.DateField(),
        ),
    ]
