# Generated by Django 5.0.6 on 2024-07-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='code',
            new_name='codehive_id',
        ),
        migrations.AddField(
            model_name='student',
            name='student_guardian',
            field=models.CharField(default=23, max_length=20),
            preserve_default=False,
        ),
    ]
